[package]
name = "bracha_broadcast"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = {version = "0.29.0", features = ["poll"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
